# Generated by Django 4.2.4 on 2023-09-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_Jazz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banda_o_compositor_musical', models.CharField(max_length=40)),
                ('Decada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Pop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banda_o_compositor_musical', models.CharField(max_length=40)),
                ('Decada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banda_o_compositor_musical', models.CharField(max_length=40)),
                ('Decada', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Tango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banda_o_compositor_musical', models.CharField(max_length=40)),
                ('Decada', models.DateTimeField()),
            ],
        ),
    ]
