# Generated by Django 4.2.4 on 2023-09-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista_jazz',
            name='Decada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lista_pop',
            name='Decada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lista_rock',
            name='Decada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lista_tango',
            name='Decada',
            field=models.IntegerField(),
        ),
    ]
